### ISSUE TITLE
There is an issue with the assignment of both the AdRplRight and the Site rights and the error is not being captured clearly. 

### ISSUE THREAD

**Issue by wajakx** [vreguibar/EguibarIT#7]

**Comment by wajakx** [comment]
I will attach files when and erroring section when i am in position later. I believe it might be a bug or the environment on my side. When i do the assignment of all the replication based rights manually, it works after working and loading the psdrive AD and working from that location.

**Comment by vreguibar** [comment]
Hi,

Is it possible to extract the ACLs you are mentioning by using:
`Get-AclAccessRule -LDAPpath "OU=Users,OU=Good,OU=Sites,DC=EguibarIT,DC=local"`
This CMDlet is available on EguibarIT.delegation module. This will show all ACLs defined on the given LDAP path, so I can compare to what you are mentionng.
TX
